project:
  type: website
  output-dir: docs

key: value

website:
  title: "Jung Mee Park, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

