project:
  type: website
  output-dir: docs

key: value

website:
  title: "jmp243.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

